// LIST
export const GET_GISTS_ALL = 'GET_GISTS_ALL';
export const GET_GISTS_ALL_ERROR = 'GET_GISTS_ALL_ERROR';
export const GET_GISTS_BY_USER = 'GET_GISTS_BY_USER';
export const GET_GISTS_BY_USER_ERROR = 'GET_GISTS_BY_USER_ERROR';

// DETAILS
export const GET_DETAILS = 'GET_DETAILS';
export const GET_DETAILS_ERROR = 'GET_DETAILS_ERROR';
